-- MySQL Script generated by MySQL Workbench
-- 10/23/19 10:05:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_cargaacademicalectiva
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_cargaacademicalectiva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_cargaacademicalectiva` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bd_cargaacademicalectiva` ;

-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`tb_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`tb_tipo` (
  `idtb_tipo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idtb_tipo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`tb_ciclo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`tb_ciclo` (
  `idtb_ciclo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `idtb_tipo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idtb_ciclo`)  COMMENT '',
  INDEX `fk_tb_ciclo_tb_tipo1_idx` (`idtb_tipo` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_ciclo_tb_tipo1`
    FOREIGN KEY (`idtb_tipo`)
    REFERENCES `bd_cargaacademicalectiva`.`tb_tipo` (`idtb_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`tb_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`tb_curso` (
  `idtb_curso` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `codigo` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(100) NULL COMMENT '',
  `creditos` VARCHAR(45) NULL COMMENT '',
  `idtb_ciclo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idtb_curso`)  COMMENT '',
  INDEX `fk_tb_curso_tb_ciclo1_idx` (`idtb_ciclo` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_curso_tb_ciclo1`
    FOREIGN KEY (`idtb_ciclo`)
    REFERENCES `bd_cargaacademicalectiva`.`tb_ciclo` (`idtb_ciclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`tb_seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`tb_seccion` (
  `idtb_seccion` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idtb_seccion`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`tb_turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`tb_turno` (
  `idtb_turno` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `codigo` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idtb_turno`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`tb_semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`tb_semestre` (
  `idtb_semestre` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `idtb_tipo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idtb_semestre`)  COMMENT '',
  INDEX `fk_tb_semestre_tb_tipo1_idx` (`idtb_tipo` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_semestre_tb_tipo1`
    FOREIGN KEY (`idtb_tipo`)
    REFERENCES `bd_cargaacademicalectiva`.`tb_tipo` (`idtb_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`tb_tipo_docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`tb_tipo_docente` (
  `idtb_tipo_docente` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idtb_tipo_docente`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`tb_tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`tb_tipo_usuario` (
  `idtb_tipo_usuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idtb_tipo_usuario`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`tb_usuario` (
  `idtb_usuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `apellido` VARCHAR(45) NULL COMMENT '',
  `usuario` VARCHAR(45) NULL COMMENT '',
  `clave` VARCHAR(45) NULL COMMENT '',
  `idtb_tipo_usuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idtb_usuario`)  COMMENT '',
  INDEX `fk_tb_usuario_tb_tipo_usuario1_idx` (`idtb_tipo_usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_usuario_tb_tipo_usuario1`
    FOREIGN KEY (`idtb_tipo_usuario`)
    REFERENCES `bd_cargaacademicalectiva`.`tb_tipo_usuario` (`idtb_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`tb_docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`tb_docente` (
  `idtb_docente` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `codigo` VARCHAR(45) NULL COMMENT '',
  `documento` VARCHAR(45) NULL COMMENT '',
  `idtb_tipo_docente` INT NOT NULL COMMENT '',
  `idtb_usuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idtb_docente`)  COMMENT '',
  INDEX `fk_tb_docente_tb_tipo_docente1_idx` (`idtb_tipo_docente` ASC)  COMMENT '',
  INDEX `fk_tb_docente_tb_usuario1_idx` (`idtb_usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_docente_tb_tipo_docente1`
    FOREIGN KEY (`idtb_tipo_docente`)
    REFERENCES `bd_cargaacademicalectiva`.`tb_tipo_docente` (`idtb_tipo_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_docente_tb_usuario1`
    FOREIGN KEY (`idtb_usuario`)
    REFERENCES `bd_cargaacademicalectiva`.`tb_usuario` (`idtb_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`tb_carga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`tb_carga` (
  `idtb_carga` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idtb_seccion` INT NOT NULL COMMENT '',
  `idtb_turno` INT NOT NULL COMMENT '',
  `idtb_curso` INT NOT NULL COMMENT '',
  `idtb_semestre` INT NOT NULL COMMENT '',
  `idtb_docente` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idtb_carga`)  COMMENT '',
  INDEX `fk_tb_plaza_tb_curso_idx` (`idtb_curso` ASC)  COMMENT '',
  INDEX `fk_tb_plaza_tb_seccion1_idx` (`idtb_seccion` ASC)  COMMENT '',
  INDEX `fk_tb_plaza_tb_turno1_idx` (`idtb_turno` ASC)  COMMENT '',
  INDEX `fk_tb_plaza_tb_semestre1_idx` (`idtb_semestre` ASC)  COMMENT '',
  INDEX `fk_tb_carga_tb_docente1_idx` (`idtb_docente` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_plaza_tb_curso`
    FOREIGN KEY (`idtb_curso`)
    REFERENCES `bd_cargaacademicalectiva`.`tb_curso` (`idtb_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_plaza_tb_seccion1`
    FOREIGN KEY (`idtb_seccion`)
    REFERENCES `bd_cargaacademicalectiva`.`tb_seccion` (`idtb_seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_plaza_tb_turno1`
    FOREIGN KEY (`idtb_turno`)
    REFERENCES `bd_cargaacademicalectiva`.`tb_turno` (`idtb_turno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_plaza_tb_semestre1`
    FOREIGN KEY (`idtb_semestre`)
    REFERENCES `bd_cargaacademicalectiva`.`tb_semestre` (`idtb_semestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_carga_tb_docente1`
    FOREIGN KEY (`idtb_docente`)
    REFERENCES `bd_cargaacademicalectiva`.`tb_docente` (`idtb_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`tb_dia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`tb_dia` (
  `idtb_dia` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idtb_dia`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`tb_horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`tb_horario` (
  `idtb_horario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `hora_inicio` VARCHAR(45) NULL COMMENT '',
  `hora_fin` VARCHAR(45) NULL COMMENT '',
  `idtb_dia` INT NOT NULL COMMENT '',
  `idtb_carga` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idtb_horario`)  COMMENT '',
  INDEX `fk_tb_horario_tb_dia1_idx` (`idtb_dia` ASC)  COMMENT '',
  INDEX `fk_tb_horario_tb_carga1_idx` (`idtb_carga` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_horario_tb_dia1`
    FOREIGN KEY (`idtb_dia`)
    REFERENCES `bd_cargaacademicalectiva`.`tb_dia` (`idtb_dia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_horario_tb_carga1`
    FOREIGN KEY (`idtb_carga`)
    REFERENCES `bd_cargaacademicalectiva`.`tb_carga` (`idtb_carga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`tb_carga_no_lectiva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`tb_carga_no_lectiva` (
  `idtb_carga_no_lectiva` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `actividad` VARCHAR(45) NULL COMMENT '',
  `horas` VARCHAR(45) NULL COMMENT '',
  `idtb_docente` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idtb_carga_no_lectiva`)  COMMENT '',
  INDEX `fk_tb_carga_no_lectiva_tb_docente1_idx` (`idtb_docente` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_carga_no_lectiva_tb_docente1`
    FOREIGN KEY (`idtb_docente`)
    REFERENCES `bd_cargaacademicalectiva`.`tb_docente` (`idtb_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
