-- MySQL Script generated by MySQL Workbench
-- 11/19/19 17:35:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_cargaacademicalectiva
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_cargaacademicalectiva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_cargaacademicalectiva` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bd_cargaacademicalectiva` ;

-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`tipo` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`ciclo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`ciclo` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `id_semestre` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `id_tipo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_tb_ciclo_tb_tipo1_idx` (`id_tipo` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_ciclo_tb_tipo1`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `bd_cargaacademicalectiva`.`tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`curso` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(100) NULL COMMENT '',
  `codigo` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(100) NULL COMMENT '',
  `creditos` VARCHAR(45) NULL COMMENT '',
  `id_periodo` VARCHAR(45) NULL COMMENT '',
  `id_ciclo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_tb_curso_tb_ciclo1_idx` (`id_ciclo` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_curso_tb_ciclo1`
    FOREIGN KEY (`id_ciclo`)
    REFERENCES `bd_cargaacademicalectiva`.`ciclo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`seccion` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`turno` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `codigo` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`semestre` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `numero` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `id_tipo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_tb_semestre_tb_tipo1_idx` (`id_tipo` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_semestre_tb_tipo1`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `bd_cargaacademicalectiva`.`tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`tipo_docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`tipo_docente` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`docente` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `apellido_paterno` VARCHAR(45) NULL COMMENT '',
  `apellido_materno` VARCHAR(45) NULL COMMENT '',
  `nombres` VARCHAR(45) NULL COMMENT '',
  `telefono` VARCHAR(45) NULL COMMENT '',
  `id_direccion` VARCHAR(45) NULL COMMENT '',
  `correo` VARCHAR(45) NULL COMMENT '',
  `jefe_departamento` VARCHAR(45) NULL COMMENT '',
  `id_postulante` VARCHAR(45) NULL COMMENT '',
  `id_tipo_docente` INT NOT NULL COMMENT '',
  `usuario` VARCHAR(45) NULL COMMENT '',
  `clave` VARCHAR(45) NULL COMMENT '',
  `estado` VARCHAR(45) NULL COMMENT '',
  `dni` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_tb_docente_tb_tipo_docente1_idx` (`id_tipo_docente` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_docente_tb_tipo_docente1`
    FOREIGN KEY (`id_tipo_docente`)
    REFERENCES `bd_cargaacademicalectiva`.`tipo_docente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`carga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`carga` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_seccion` INT NOT NULL COMMENT '',
  `id_turno` INT NOT NULL COMMENT '',
  `id_curso` INT NOT NULL COMMENT '',
  `id_semestre` INT NOT NULL COMMENT '',
  `id_docente` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_tb_plaza_tb_curso_idx` (`id_curso` ASC)  COMMENT '',
  INDEX `fk_tb_plaza_tb_seccion1_idx` (`id_seccion` ASC)  COMMENT '',
  INDEX `fk_tb_plaza_tb_turno1_idx` (`id_turno` ASC)  COMMENT '',
  INDEX `fk_tb_plaza_tb_semestre1_idx` (`id_semestre` ASC)  COMMENT '',
  INDEX `fk_tb_carga_tb_docente1_idx` (`id_docente` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_plaza_tb_curso`
    FOREIGN KEY (`id_curso`)
    REFERENCES `bd_cargaacademicalectiva`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_plaza_tb_seccion1`
    FOREIGN KEY (`id_seccion`)
    REFERENCES `bd_cargaacademicalectiva`.`seccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_plaza_tb_turno1`
    FOREIGN KEY (`id_turno`)
    REFERENCES `bd_cargaacademicalectiva`.`turno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_plaza_tb_semestre1`
    FOREIGN KEY (`id_semestre`)
    REFERENCES `bd_cargaacademicalectiva`.`semestre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_carga_tb_docente1`
    FOREIGN KEY (`id_docente`)
    REFERENCES `bd_cargaacademicalectiva`.`docente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`dia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`dia` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`horario` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `hora_inicio` VARCHAR(45) NULL COMMENT '',
  `hora_final` VARCHAR(45) NULL COMMENT '',
  `id_dia` INT NOT NULL COMMENT '',
  `id_carga` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_tb_horario_tb_dia1_idx` (`id_dia` ASC)  COMMENT '',
  INDEX `fk_tb_horario_tb_carga1_idx` (`id_carga` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_horario_tb_dia1`
    FOREIGN KEY (`id_dia`)
    REFERENCES `bd_cargaacademicalectiva`.`dia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_horario_tb_carga1`
    FOREIGN KEY (`id_carga`)
    REFERENCES `bd_cargaacademicalectiva`.`carga` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`actividad` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`carga_no_lectiva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`carga_no_lectiva` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `horas` VARCHAR(45) NULL COMMENT '',
  `id_docente` INT NOT NULL COMMENT '',
  `id_actividad` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_tb_carga_no_lectiva_tb_docente1_idx` (`id_docente` ASC)  COMMENT '',
  INDEX `fk_tb_carga_no_lectiva_tb_actividad1_idx` (`id_actividad` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_carga_no_lectiva_tb_docente1`
    FOREIGN KEY (`id_docente`)
    REFERENCES `bd_cargaacademicalectiva`.`docente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_carga_no_lectiva_tb_actividad1`
    FOREIGN KEY (`id_actividad`)
    REFERENCES `bd_cargaacademicalectiva`.`actividad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`numero_semana`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`numero_semana` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`plan_de_trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`plan_de_trabajo` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `id_carga_no_lectiva` INT NOT NULL COMMENT '',
  `id_numero_semana` INT NOT NULL COMMENT '',
  `cumplimiento` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_tb_plan_de_trabajo_tb_carga_no_lectiva1_idx` (`id_carga_no_lectiva` ASC)  COMMENT '',
  INDEX `fk_tb_plan_de_trabajo_tb_numero_semana1_idx` (`id_numero_semana` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_plan_de_trabajo_tb_carga_no_lectiva1`
    FOREIGN KEY (`id_carga_no_lectiva`)
    REFERENCES `bd_cargaacademicalectiva`.`carga_no_lectiva` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_plan_de_trabajo_tb_numero_semana1`
    FOREIGN KEY (`id_numero_semana`)
    REFERENCES `bd_cargaacademicalectiva`.`numero_semana` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`carga_no_lectiva_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`carga_no_lectiva_detalle` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `id_plan_de_trabajo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_tb_carga_no_lectiva_detalle_tb_plan_de_trabajo1_idx` (`id_plan_de_trabajo` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_carga_no_lectiva_detalle_tb_plan_de_trabajo1`
    FOREIGN KEY (`id_plan_de_trabajo`)
    REFERENCES `bd_cargaacademicalectiva`.`plan_de_trabajo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`cumplimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`cumplimiento` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cumplio` VARCHAR(45) NULL COMMENT '',
  `id_plan_de_trabajo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_tb_cumplimiento_tb_plan_de_trabajo1_idx` (`id_plan_de_trabajo` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_cumplimiento_tb_plan_de_trabajo1`
    FOREIGN KEY (`id_plan_de_trabajo`)
    REFERENCES `bd_cargaacademicalectiva`.`plan_de_trabajo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
