-- MySQL Script generated by MySQL Workbench
-- 11/18/19 20:06:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_cargaacademicalectiva
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_cargaacademicalectiva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_cargaacademicalectiva` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bd_cargaacademicalectiva` ;

-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`tipo` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_tipo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`ciclo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`ciclo` (
  `id_ciclo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `id_tipo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_ciclo`)  COMMENT '',
  INDEX `fk_tb_ciclo_tb_tipo1_idx` (`id_tipo` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_ciclo_tb_tipo1`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `bd_cargaacademicalectiva`.`tipo` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `codigo` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(100) NULL COMMENT '',
  `creditos` VARCHAR(45) NULL COMMENT '',
  `id_ciclo` INT NOT NULL COMMENT '',
  `horas` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_curso`)  COMMENT '',
  INDEX `fk_tb_curso_tb_ciclo1_idx` (`id_ciclo` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_curso_tb_ciclo1`
    FOREIGN KEY (`id_ciclo`)
    REFERENCES `bd_cargaacademicalectiva`.`ciclo` (`id_ciclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`seccion` (
  `id_seccion` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_seccion`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`turno` (
  `id_turno` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `codigo` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_turno`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`semestre` (
  `id_semestre` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `id_tipo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_semestre`)  COMMENT '',
  INDEX `fk_tb_semestre_tb_tipo1_idx` (`id_tipo` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_semestre_tb_tipo1`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `bd_cargaacademicalectiva`.`tipo` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`tipo_docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`tipo_docente` (
  `id_tipo_docente` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_tipo_docente`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`tipo_usuario` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_tipo_usuario`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `apellido` VARCHAR(45) NULL COMMENT '',
  `usuario` VARCHAR(45) NULL COMMENT '',
  `clave` VARCHAR(45) NULL COMMENT '',
  `id_tipo_usuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_usuario`)  COMMENT '',
  INDEX `fk_tb_usuario_tb_tipo_usuario1_idx` (`id_tipo_usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_usuario_tb_tipo_usuario1`
    FOREIGN KEY (`id_tipo_usuario`)
    REFERENCES `bd_cargaacademicalectiva`.`tipo_usuario` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`docente` (
  `id_docente` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `codigo` VARCHAR(45) NULL COMMENT '',
  `documento` VARCHAR(45) NULL COMMENT '',
  `id_tipo_docente` INT NOT NULL COMMENT '',
  `id_usuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_docente`)  COMMENT '',
  INDEX `fk_tb_docente_tb_tipo_docente1_idx` (`id_tipo_docente` ASC)  COMMENT '',
  INDEX `fk_tb_docente_tb_usuario1_idx` (`id_usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_docente_tb_tipo_docente1`
    FOREIGN KEY (`id_tipo_docente`)
    REFERENCES `bd_cargaacademicalectiva`.`tipo_docente` (`id_tipo_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_docente_tb_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bd_cargaacademicalectiva`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`carga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`carga` (
  `id_carga` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_seccion` INT NOT NULL COMMENT '',
  `id_turno` INT NOT NULL COMMENT '',
  `id_curso` INT NOT NULL COMMENT '',
  `id_semestre` INT NOT NULL COMMENT '',
  `id_docente` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_carga`)  COMMENT '',
  INDEX `fk_tb_plaza_tb_curso_idx` (`id_curso` ASC)  COMMENT '',
  INDEX `fk_tb_plaza_tb_seccion1_idx` (`id_seccion` ASC)  COMMENT '',
  INDEX `fk_tb_plaza_tb_turno1_idx` (`id_turno` ASC)  COMMENT '',
  INDEX `fk_tb_plaza_tb_semestre1_idx` (`id_semestre` ASC)  COMMENT '',
  INDEX `fk_tb_carga_tb_docente1_idx` (`id_docente` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_plaza_tb_curso`
    FOREIGN KEY (`id_curso`)
    REFERENCES `bd_cargaacademicalectiva`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_plaza_tb_seccion1`
    FOREIGN KEY (`id_seccion`)
    REFERENCES `bd_cargaacademicalectiva`.`seccion` (`id_seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_plaza_tb_turno1`
    FOREIGN KEY (`id_turno`)
    REFERENCES `bd_cargaacademicalectiva`.`turno` (`id_turno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_plaza_tb_semestre1`
    FOREIGN KEY (`id_semestre`)
    REFERENCES `bd_cargaacademicalectiva`.`semestre` (`id_semestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_carga_tb_docente1`
    FOREIGN KEY (`id_docente`)
    REFERENCES `bd_cargaacademicalectiva`.`docente` (`id_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`dia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`dia` (
  `id_dia` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_dia`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`horario` (
  `id_horario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `hora_inicio` VARCHAR(45) NULL COMMENT '',
  `hora_fin` VARCHAR(45) NULL COMMENT '',
  `id_dia` INT NOT NULL COMMENT '',
  `id_carga` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_horario`)  COMMENT '',
  INDEX `fk_tb_horario_tb_dia1_idx` (`id_dia` ASC)  COMMENT '',
  INDEX `fk_tb_horario_tb_carga1_idx` (`id_carga` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_horario_tb_dia1`
    FOREIGN KEY (`id_dia`)
    REFERENCES `bd_cargaacademicalectiva`.`dia` (`id_dia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_horario_tb_carga1`
    FOREIGN KEY (`id_carga`)
    REFERENCES `bd_cargaacademicalectiva`.`carga` (`id_carga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`actividad` (
  `id_actividad` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_actividad`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`carga_no_lectiva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`carga_no_lectiva` (
  `id_carga_no_lectiva` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `horas` VARCHAR(45) NULL COMMENT '',
  `id_docente` INT NOT NULL COMMENT '',
  `id_actividad` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_carga_no_lectiva`)  COMMENT '',
  INDEX `fk_tb_carga_no_lectiva_tb_docente1_idx` (`id_docente` ASC)  COMMENT '',
  INDEX `fk_tb_carga_no_lectiva_tb_actividad1_idx` (`id_actividad` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_carga_no_lectiva_tb_docente1`
    FOREIGN KEY (`id_docente`)
    REFERENCES `bd_cargaacademicalectiva`.`docente` (`id_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_carga_no_lectiva_tb_actividad1`
    FOREIGN KEY (`id_actividad`)
    REFERENCES `bd_cargaacademicalectiva`.`actividad` (`id_actividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`numero_semana`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`numero_semana` (
  `id_numero_semana` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_numero_semana`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`plan_de_trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`plan_de_trabajo` (
  `id_plan_de_trabajo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `id_carga_no_lectiva` INT NOT NULL COMMENT '',
  `id_numero_semana` INT NOT NULL COMMENT '',
  `cumplimiento` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_plan_de_trabajo`)  COMMENT '',
  INDEX `fk_tb_plan_de_trabajo_tb_carga_no_lectiva1_idx` (`id_carga_no_lectiva` ASC)  COMMENT '',
  INDEX `fk_tb_plan_de_trabajo_tb_numero_semana1_idx` (`id_numero_semana` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_plan_de_trabajo_tb_carga_no_lectiva1`
    FOREIGN KEY (`id_carga_no_lectiva`)
    REFERENCES `bd_cargaacademicalectiva`.`carga_no_lectiva` (`id_carga_no_lectiva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_plan_de_trabajo_tb_numero_semana1`
    FOREIGN KEY (`id_numero_semana`)
    REFERENCES `bd_cargaacademicalectiva`.`numero_semana` (`id_numero_semana`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`carga_no_lectiva_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`carga_no_lectiva_detalle` (
  `id_carga_no_lectiva_detalle` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `id_plan_de_trabajo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_carga_no_lectiva_detalle`)  COMMENT '',
  INDEX `fk_tb_carga_no_lectiva_detalle_tb_plan_de_trabajo1_idx` (`id_plan_de_trabajo` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_carga_no_lectiva_detalle_tb_plan_de_trabajo1`
    FOREIGN KEY (`id_plan_de_trabajo`)
    REFERENCES `bd_cargaacademicalectiva`.`plan_de_trabajo` (`id_plan_de_trabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`cumplimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`cumplimiento` (
  `id_cumplimiento` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cumplio` VARCHAR(45) NULL COMMENT '',
  `id_plan_de_trabajo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_cumplimiento`)  COMMENT '',
  INDEX `fk_tb_cumplimiento_tb_plan_de_trabajo1_idx` (`id_plan_de_trabajo` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_cumplimiento_tb_plan_de_trabajo1`
    FOREIGN KEY (`id_plan_de_trabajo`)
    REFERENCES `bd_cargaacademicalectiva`.`plan_de_trabajo` (`id_plan_de_trabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`menu` (
  `id_menu` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `url` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_menu`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`permiso` (
  `id_permiso` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `create` VARCHAR(45) NULL COMMENT '',
  `read` VARCHAR(45) NULL COMMENT '',
  `update` VARCHAR(45) NULL COMMENT '',
  `delete` VARCHAR(45) NULL COMMENT '',
  `id_menu` INT NOT NULL COMMENT '',
  `id_tipo_usuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_permiso`)  COMMENT '',
  INDEX `fk_tb_permisos_tb_menu1_idx` (`id_menu` ASC)  COMMENT '',
  INDEX `fk_tb_permisos_tb_tipo_usuario1_idx` (`id_tipo_usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_permisos_tb_menu1`
    FOREIGN KEY (`id_menu`)
    REFERENCES `bd_cargaacademicalectiva`.`menu` (`id_menu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_permisos_tb_tipo_usuario1`
    FOREIGN KEY (`id_tipo_usuario`)
    REFERENCES `bd_cargaacademicalectiva`.`tipo_usuario` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
