-- MySQL Script generated by MySQL Workbench
-- 11/18/19 18:22:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_cargaacademicalectiva
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_cargaacademicalectiva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_cargaacademicalectiva` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bd_cargaacademicalectiva` ;

-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`tipo` (
  `tipo_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`tipo_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`ciclo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`ciclo` (
  `ciclo_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `tipo_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ciclo_id`)  COMMENT '',
  INDEX `fk_tb_ciclo_tb_tipo1_idx` (`tipo_id` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_ciclo_tb_tipo1`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `bd_cargaacademicalectiva`.`tipo` (`tipo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`curso` (
  `curso_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `codigo` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(100) NULL COMMENT '',
  `creditos` VARCHAR(45) NULL COMMENT '',
  `ciclo_id` INT NOT NULL COMMENT '',
  `horas` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`curso_id`)  COMMENT '',
  INDEX `fk_tb_curso_tb_ciclo1_idx` (`ciclo_id` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_curso_tb_ciclo1`
    FOREIGN KEY (`ciclo_id`)
    REFERENCES `bd_cargaacademicalectiva`.`ciclo` (`ciclo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`seccion` (
  `seccion_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`seccion_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`turno` (
  `turno_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `codigo` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`turno_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`semestre` (
  `semestre_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `tipo_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`semestre_id`)  COMMENT '',
  INDEX `fk_tb_semestre_tb_tipo1_idx` (`tipo_id` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_semestre_tb_tipo1`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `bd_cargaacademicalectiva`.`tipo` (`tipo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`tipo_docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`tipo_docente` (
  `tipo_docente_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`tipo_docente_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`tipo_usuario` (
  `tipo_usuario_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`tipo_usuario_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `apellido` VARCHAR(45) NULL COMMENT '',
  `usuario` VARCHAR(45) NULL COMMENT '',
  `clave` VARCHAR(45) NULL COMMENT '',
  `tipo_usuario_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`usuario_id`)  COMMENT '',
  INDEX `fk_tb_usuario_tb_tipo_usuario1_idx` (`tipo_usuario_id` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_usuario_tb_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario_id`)
    REFERENCES `bd_cargaacademicalectiva`.`tipo_usuario` (`tipo_usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`docente` (
  `docente_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `codigo` VARCHAR(45) NULL COMMENT '',
  `documento` VARCHAR(45) NULL COMMENT '',
  `tipo_docente_id` INT NOT NULL COMMENT '',
  `usuario_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`docente_id`)  COMMENT '',
  INDEX `fk_tb_docente_tb_tipo_docente1_idx` (`tipo_docente_id` ASC)  COMMENT '',
  INDEX `fk_tb_docente_tb_usuario1_idx` (`usuario_id` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_docente_tb_tipo_docente1`
    FOREIGN KEY (`tipo_docente_id`)
    REFERENCES `bd_cargaacademicalectiva`.`tipo_docente` (`tipo_docente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_docente_tb_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `bd_cargaacademicalectiva`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`carga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`carga` (
  `carga_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `seccion_id` INT NOT NULL COMMENT '',
  `turno_id` INT NOT NULL COMMENT '',
  `curso_id` INT NOT NULL COMMENT '',
  `semestre_id` INT NOT NULL COMMENT '',
  `docente_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`carga_id`)  COMMENT '',
  INDEX `fk_tb_plaza_tb_curso_idx` (`curso_id` ASC)  COMMENT '',
  INDEX `fk_tb_plaza_tb_seccion1_idx` (`seccion_id` ASC)  COMMENT '',
  INDEX `fk_tb_plaza_tb_turno1_idx` (`turno_id` ASC)  COMMENT '',
  INDEX `fk_tb_plaza_tb_semestre1_idx` (`semestre_id` ASC)  COMMENT '',
  INDEX `fk_tb_carga_tb_docente1_idx` (`docente_id` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_plaza_tb_curso`
    FOREIGN KEY (`curso_id`)
    REFERENCES `bd_cargaacademicalectiva`.`curso` (`curso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_plaza_tb_seccion1`
    FOREIGN KEY (`seccion_id`)
    REFERENCES `bd_cargaacademicalectiva`.`seccion` (`seccion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_plaza_tb_turno1`
    FOREIGN KEY (`turno_id`)
    REFERENCES `bd_cargaacademicalectiva`.`turno` (`turno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_plaza_tb_semestre1`
    FOREIGN KEY (`semestre_id`)
    REFERENCES `bd_cargaacademicalectiva`.`semestre` (`semestre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_carga_tb_docente1`
    FOREIGN KEY (`docente_id`)
    REFERENCES `bd_cargaacademicalectiva`.`docente` (`docente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`dia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`dia` (
  `dia_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`dia_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`horario` (
  `horario_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `hora_inicio` VARCHAR(45) NULL COMMENT '',
  `hora_fin` VARCHAR(45) NULL COMMENT '',
  `dia_id` INT NOT NULL COMMENT '',
  `carga_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`horario_id`)  COMMENT '',
  INDEX `fk_tb_horario_tb_dia1_idx` (`dia_id` ASC)  COMMENT '',
  INDEX `fk_tb_horario_tb_carga1_idx` (`carga_id` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_horario_tb_dia1`
    FOREIGN KEY (`dia_id`)
    REFERENCES `bd_cargaacademicalectiva`.`dia` (`dia_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_horario_tb_carga1`
    FOREIGN KEY (`carga_id`)
    REFERENCES `bd_cargaacademicalectiva`.`carga` (`carga_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`actividad` (
  `actividad_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`actividad_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`carga_no_lectiva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`carga_no_lectiva` (
  `carga_no_lectiva_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `horas` VARCHAR(45) NULL COMMENT '',
  `docente_id` INT NOT NULL COMMENT '',
  `actividad_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`carga_no_lectiva_id`)  COMMENT '',
  INDEX `fk_tb_carga_no_lectiva_tb_docente1_idx` (`docente_id` ASC)  COMMENT '',
  INDEX `fk_tb_carga_no_lectiva_tb_actividad1_idx` (`actividad_id` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_carga_no_lectiva_tb_docente1`
    FOREIGN KEY (`docente_id`)
    REFERENCES `bd_cargaacademicalectiva`.`docente` (`docente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_carga_no_lectiva_tb_actividad1`
    FOREIGN KEY (`actividad_id`)
    REFERENCES `bd_cargaacademicalectiva`.`actividad` (`actividad_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`numero_semana`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`numero_semana` (
  `numero_semana_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`numero_semana_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`plan_de_trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`plan_de_trabajo` (
  `plan_de_trabajo_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `carga_no_lectiva_id` INT NOT NULL COMMENT '',
  `numero_semana_id` INT NOT NULL COMMENT '',
  `cumplimiento` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`plan_de_trabajo_id`)  COMMENT '',
  INDEX `fk_tb_plan_de_trabajo_tb_carga_no_lectiva1_idx` (`carga_no_lectiva_id` ASC)  COMMENT '',
  INDEX `fk_tb_plan_de_trabajo_tb_numero_semana1_idx` (`numero_semana_id` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_plan_de_trabajo_tb_carga_no_lectiva1`
    FOREIGN KEY (`carga_no_lectiva_id`)
    REFERENCES `bd_cargaacademicalectiva`.`carga_no_lectiva` (`carga_no_lectiva_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_plan_de_trabajo_tb_numero_semana1`
    FOREIGN KEY (`numero_semana_id`)
    REFERENCES `bd_cargaacademicalectiva`.`numero_semana` (`numero_semana_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`carga_no_lectiva_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`carga_no_lectiva_detalle` (
  `carga_no_lectiva_detalle_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `plan_de_trabajo_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`carga_no_lectiva_detalle_id`)  COMMENT '',
  INDEX `fk_tb_carga_no_lectiva_detalle_tb_plan_de_trabajo1_idx` (`plan_de_trabajo_id` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_carga_no_lectiva_detalle_tb_plan_de_trabajo1`
    FOREIGN KEY (`plan_de_trabajo_id`)
    REFERENCES `bd_cargaacademicalectiva`.`plan_de_trabajo` (`plan_de_trabajo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`cumplimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`cumplimiento` (
  `cumplimiento_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cumplio` VARCHAR(45) NULL COMMENT '',
  `plan_de_trabajo_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`cumplimiento_id`)  COMMENT '',
  INDEX `fk_tb_cumplimiento_tb_plan_de_trabajo1_idx` (`plan_de_trabajo_id` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_cumplimiento_tb_plan_de_trabajo1`
    FOREIGN KEY (`plan_de_trabajo_id`)
    REFERENCES `bd_cargaacademicalectiva`.`plan_de_trabajo` (`plan_de_trabajo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`menu` (
  `menu_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `url` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`menu_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cargaacademicalectiva`.`permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_cargaacademicalectiva`.`permiso` (
  `permiso_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `create` VARCHAR(45) NULL COMMENT '',
  `read` VARCHAR(45) NULL COMMENT '',
  `update` VARCHAR(45) NULL COMMENT '',
  `delete` VARCHAR(45) NULL COMMENT '',
  `menu_id` INT NOT NULL COMMENT '',
  `tipo_usuario_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`permiso_id`)  COMMENT '',
  INDEX `fk_tb_permisos_tb_menu1_idx` (`menu_id` ASC)  COMMENT '',
  INDEX `fk_tb_permisos_tb_tipo_usuario1_idx` (`tipo_usuario_id` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_permisos_tb_menu1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `bd_cargaacademicalectiva`.`menu` (`menu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_permisos_tb_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario_id`)
    REFERENCES `bd_cargaacademicalectiva`.`tipo_usuario` (`tipo_usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
